- name: Set block device partition prefix
  set_fact:
    main_block_device_partition_prefix: "\
      {% if user_data.setup_params.main_block_device_name.startswith('nvme') %}\
      {{ user_data.setup_params.main_block_device_name }}p\
      {% else %}\
      {{ user_data.setup_params.main_block_device_name }}\
      {% endif %}"
- name: Create the Gentoo System
  block:
    - import_tasks: set-up-filesystems.yml
    - import_tasks: distribute-gentoo-stage3-archive.yml
    - import_tasks: distribute-gentoo-snapshot-archive.yml
    - import_tasks: prepare-chroot.yml
