- name: Set block device partition prefix
  set_fact:
    main_block_device_partition_prefix: "\
      {% if user_data.setup_params.main_block_device_name.startswith('nvme') %}\
      {{ user_data.setup_params.main_block_device_name }}p\
      {% else %}\
      {{ user_data.setup_params.main_block_device_name }}\
      {% endif %}"
- name: Create the Gentoo System
  block:
    - import_tasks: set-up-filesystems.yml
    - import_tasks: distribute-gentoo-stage3-archive.yml
    - import_tasks: distribute-gentoo-snapshot-archive.yml
    - import_tasks: prepare-chroot.yml

- name: Set up SSHd alt port
  block:
    - name: Start SSHd
      changed_when: no
      command: >-
        /usr/sbin/sshd
        -o ChrootDirectory=/mnt/gentoo
        -o SetEnv=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
        -p {{ alt_sshd_port }}
    - name: Change the SSH port to the alt port
      set_fact:
        ansible_port: >-
          {{ alt_sshd_port }}

- name: Set up the Gentoo System on chroot
  block:
    - import_tasks: pre-configure-system.yml

- name: Restore the SSH port to default port
  set_fact:
    ansible_port: 22
