- name: Download latest gentoo snapshot archive
  run_once: True
  block:
    - name: Download latest snapshot DIGESTS
      local_action:
        module: ansible.builtin.get_url
        dest: >-
          {{ user_data.setup_params.portage.local_working_dir_prefix }}
        url: >-
          {{ user_data.setup_params.portage.mirror_uri }}/snapshots/portage-latest.tar.xz.md5sum
    - name: Verify exists snapshot archive
      changed_when: no
      ignore_errors: yes
      local_action:
        module: ansible.builtin.shell
        cmd: >-
          md5sum
          --check {{ user_data.setup_params.portage.local_working_dir_prefix }}/portage-latest.tar.xz.md5sum
          2> /dev/null
          | grep -E '^portage-latest.tar.xz:\s+OK$'
        args:
          chdir: >-
            {{ user_data.setup_params.portage.local_working_dir_prefix }}
      register: latest_snapshot_archive_verified
    - name: Download portage snapshot archive
      local_action:
        module: ansible.builtin.get_url
        dest: >-
          {{ user_data.setup_params.portage.local_working_dir_prefix }}
        url: >-
          {{ user_data.setup_params.portage.mirror_uri }}/snapshots/portage-latest.tar.xz
      when: latest_snapshot_archive_verified is failed
